### ISSUE TITLE
lol wot kinetic 

### ISSUE THREAD

**Issue by delphiactual** [justrealmilk/braytech.org#12]
This `Kinetic`
![image](https://user-images.githubusercontent.com/4798491/69483481-12a9a100-0de5-11ea-82cd-9d01a2295757.png)

**Comment by justrealmilk** [comment]
ooooh what's the icon in game

**Comment by delphiactual** [comment]
https://github.com/justrealmilk/destiny-icons/blob/master/weapons/damage_kinetic.svg

**Comment by justrealmilk** [comment]
she isn't in the destiny-keys font :s

**Comment by justrealmilk** [comment]
fixed

**Comment by delphiactual** [comment]
@justrealmilk, I was wrong it was the other one. (just the top half of the icon)

https://github.com/justrealmilk/destiny-icons/blob/master/weapons/environment_hazard.svg

![fe168997-88a2-4f38-a0f7-7118d98e7903](https://user-images.githubusercontent.com/4798491/69748284-39c5e280-1105-11ea-89f4-6e4ebb3f398e.jpg)
