### ISSUE TITLE
PGCR component improvements

### ISSUE THREAD

**Issue by justrealmilk** [justrealmilk/braytech.org#122]
- Header design
- Marking specific mode types that are expected to report DNF such as patrol

**Comment by CrazyByDefault** [comment]
Also, `getHistoricalStats` always returns values for Char 0 and not for the selected character

https://github.com/justrealmilk/braytech.org/blob/42971d43e14a2d794ce3047ed0614eb3d807941e/src/utils/bungie.js#L45

**Comment by justrealmilk** [comment]
Join the discord!
