### ISSUE TITLE
Screen goes grey when hovering over a item in the Sit Rep page

### ISSUE THREAD

**Issue by iamdann** [justrealmilk/braytech.org#132]
When hovered over an item under `Equipment` in the [Sit Rep Page](https://braytech.org/4/4611686018467816451/2305843009345454525/sit-rep) screen instantly goes grey. 

![out](https://user-images.githubusercontent.com/19746471/59766838-4ebe6000-92a1-11e9-82b6-63e910178fe6.gif)

**Comment by justrealmilk** [comment]
fixxeddd
