### ISSUE TITLE
Consider adding featured weekly crucible activity to This Week page

### ISSUE THREAD

**Issue by Lalo-ATX** [justrealmilk/braytech.org#136]
This week the featured weekly crucible activity is Supremacy. I know that because I read it on Reddit. But the first place I look on Tuesday after weekly reset is Braytech. It would be kinda cool to view the weekly featured crucible activity on Braytech "this week." Might even be cool to see associated triumphs for it. Not sure how that would lay out / fit. Yeah "this week" is starting to get a lot of content on it. But I don't mind scrolling, I kinda like having it on one page and not having to click other pages.

**Comment by justrealmilk** [comment]
problem is that the featured mode isn't in the API therefore requiring manual entry at 3am 😂

so for the time being i'm afraid not
