### ISSUE TITLE
Destiny Personal assistant

### ISSUE THREAD

**Issue by chadwhitely** [justrealmilk/braytech.org#143]
I had an idea regarding an app that would help me prioritize seals based on things that are only active at certain times. This led me to the following comment on one of your reddit posts:
https://www.reddit.com/r/DestinyTheGame/comments/9wi0mw/braytechorg_but_better/e9l1g3b/?st=jybth2t9&sh=adab2969

As such, here is my plan:

- [ ] Dockerize the dev environment to make my life easier https://github.com/justrealmilk/braytech.org/pull/139
- [ ] Rename "checklists" page to something else - "World items" or something similar (@justrealmilk I'd like some advice or thoughts on this one)
- [ ] Create new "checklists2" page and move tracked triumphs to this new page [In Progress](https://github.com/chadwhitely/braytech.org/tree/checklists2)
- [ ] Allow world items to be tracked and show up on checklists2
- [ ] Allow collections to be tracked and show up on checklists2
- [ ] Add activities page (possibly already done within "this week" tab) 
- [ ] Allow activities to be tracked and show up on checklists2
- [ ] Map triumphs, collections, and world items to activities
- [ ] Show percentage on triumphs based on collections (i.e. wayfarer:"Destinations:RedWar" will show percent completion of the associated collections badge)
- [ ] Extend "this week" functionality to checklists2 to show which tracked records are available this week

Stretch goals:

- [ ] Add checklist2 layer expansion (i.e. select wayfarer seal to select all triumphs not completed->all badges not completed->all collection items not completed)
- [ ] Allow checklist to be prioritized by user
- [ ] Add suggested checklists (i.e. select all seal items that are only active on certain days/weeks)
- [ ] Quickly view tracked info for clanmantes (like issue #138)

**Comment by justrealmilk** [comment]
This is more work than I could then or now or will be able to handle. Thanks for the effort.
