### ISSUE TITLE
Add placeholder for Heroic Menagerie modifiers if character's light level doesn't meet the requirement

### ISSUE THREAD

**Issue by FlaminSarge** [justrealmilk/braytech.org#174]
Heroic Menagerie requires LL740, and its modifiers do not show up under This Week if the currently selected character doesn't meet that criteria. This can probably show a placeholder message about light level requirements in that space if the modifiers can't be shown.

I assume this also happens for other activities, as well.

**Comment by justrealmilk** [comment]
Why would this be beneficial?

**Comment by FlaminSarge** [comment]
Helps with user confusion for when the Heroic Menagerie modifiers are missing from e.g. one character while present on another (encountered this when I had two LL700 items equipped on one character, bringing me to 737).
It's just wonky to go look for that and then not see it. I assume the API does/doesn't return it based on LL?

**Comment by justrealmilk** [comment]
Indeed. It’s only available if a character has it available.
