### ISSUE TITLE
License forbids modification

### ISSUE THREAD

**Issue by KiaArmani** [justrealmilk/braytech.org#195]
Hello there,

Thank you for allowing access to the source code of braytech.org! I am very interested in the design used and this enables me to have a look at it.
Unfourtunately it is not possible to contribute to this repository without infringing your copyright as you hold "All Rights Reserved".

Please consider moving to a more free license such a GPL or MIT to allow contributions from other users. Thank you for your time!

Sincerely,
Kia.

**Comment by justrealmilk** [comment]
Previously, I was using an MIT license, but I've been subject to people engaging in activities such as wrapping Braytech in a native wrapper, adding an ad, and publishing to app stores.

An exclusive license helps me feel better about that. I welcome PRs and for developers to learn from what I build.

If this prevents you from feeling as though you can contribute, I'm sorry.
