### ISSUE TITLE
Triumph Page Lists 1 Unredeemed For MMXIX that is unredeemable

### ISSUE THREAD

**Issue by brianp** [justrealmilk/braytech.org#201]
Hey!

The MMXIX Moments of Triumph seal had to be completed by September 17th. Users who have not completed it (myself) no longer have access to it from their account. The seal has been removed from the list of seals if it was uncompleted. Last night I finished the "Crucible Pinnacle Arsenal" triumph from the seal, and Braytech lists it as such. But I can no longer claim that seal, nor redeem that triumph. 

I think seasonal triumphs may need to be date guarded.

Edited: A clarification that the seal was only removed if uncompleted.

**Comment by hmqgg** [comment]
This was fixed by hard-coded 23 items for MMXIX.

**Comment by justrealmilk** [comment]
nah I think he's referring to the unredeemed triumphs views and that he can no longer _redeem_ the records in game

i'm gonna ask the API overlord before i make my own moves on this

**Comment by brianp** [comment]
> nah I think he's referring to the unredeemed triumphs views and that he can no longer redeem the records in game

Exactly

**Comment by justrealmilk** [comment]
Would you be willing to share your gamertag @brianp

**Comment by brianp** [comment]
Shared in DM (Twitter)
