### ISSUE TITLE
I ran into a problem with the installation and asked for help

### ISSUE THREAD

**Issue by HoxtonK** [justrealmilk/braytech.org#209]
Thank you very much for asking for help

OS:Ubuntu 19.10 & 18.04
Nodejs: 10.15.2

Error running after installation

Compiled with warnings.

./src/components/Roster/index.js
  Line 104:91:  'lastMode' is assigned a value but never used  no-unused-vars

./src/views/Now/index.js
  Line 10:8:  'VanguardStrikes' is defined but never used  no-unused-vars
  Line 16:8:  'Vendor' is defined but never used           no-unused-vars

./src/views/Index/index.js
  Line 112:16:  'viewport' is assigned a value but never used            no-unused-vars
  Line 124:25:  Expected to return a value at the end of arrow function  array-callback-return

./src/components/QuestLine/index.js
  Line 11:10:  'checklists' is defined but never used  no-unused-vars
  Line 11:22:  'lookup' is defined but never used      no-unused-vars

./src/components/Maps/index.js
  Line 11:37:  'Polygon' is defined but never used  no-unused-vars

./src/views/ThisWeek/Modules/DreamingCityShatteredThrone/index.js
  Line 12:16:  'cycleInfo' is assigned a value but never used  no-unused-vars

./src/components/Search/index.js
  Line 13:10:  'allSettled' is defined but never used  no-unused-vars

./src/views/ThisWeek/index.js
  Line 35:13:  'member' is assigned a value but never used  no-unused-vars

./src/components/Tooltip/Item/fallback.js
  Line 3:8:  'cx' is defined but never used  no-unused-vars

./src/components/RosterLeaderboards/index.js
  Line 40:35:  'mode' is assigned a value but never used  no-unused-vars

./src/components/RosterAdmin/index.js
  Line 457:91:  'lastMode' is assigned a value but never used  no-unused-vars

./src/views/Clan/Admin/index.js
  Line 4:18:  'DiffProfile' is defined but never used  no-unused-vars

./src/views/Inspect/index.js
  Line 51:9:   'backLinkPath' is assigned a value but never used  no-unused-vars
  Line 76:11:  'hasBaseStat' is assigned a value but never used   no-unused-vars
  Line 78:9:   'powerLevel' is assigned a value but never used    no-unused-vars

./src/views/Now/Modules/Vendor/index.js
  Line 59:13:  't' is assigned a value but never used  no-unused-vars

./src/views/ThisWeek/Modules/FeaturedActivities/index.js
  Line 5:8:  'ReactMarkdown' is defined but never used  no-unused-vars

./src/components/Tooltip/Item/index.js
  Line 9:13:  'enums' is defined but never used  no-unused-vars

./src/views/Loading/index.js
  Line 9:8:  'ObservedImage' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by justrealmilk** [comment]
These are normal warnings.

**Comment by HoxtonK** [comment]
> 这些是正常警告。

Thank you for answers.
But the startup is not successful and cannot be accessed

**Comment by justrealmilk** [comment]
Have you tried `https://LAN_IP:3000`?

**Comment by HoxtonK** [comment]
> Have you tried `https://LAN_IP:3000`?

 Yes. I tried LAN_IP:3000 & Localhost:3000, can't access
pls help me

**Comment by justrealmilk** [comment]
You need to provide more information about the specific issue you’re having. 

To reach the output you posted above, the development server needs to successfully start so I’m not sure what the issue is.

**Comment by HoxtonK** [comment]
> You need to provide more information about the specific issue you’re having.
> 
> To reach the output you posted above, the development server needs to successfully start so I’m not sure what the issue is.

sry my friend...
It's my firewall problem
In addition, I would like to ask how to modify the default language
Thank you again for your answer

**Comment by justrealmilk** [comment]
go to Settings

**Comment by HoxtonK** [comment]
> go to Settings

 I want to set the default language for opening websites 
plz tell me thx

**Comment by HoxtonK** [comment]
Thank you very much. All the problems have been solved.
