### ISSUE TITLE
UI weirdness with Perfect Assault triumph

### ISSUE THREAD

**Issue by Lalo-ATX** [justrealmilk/braytech.org#213]
Perfect Assault triumph has a gold border/background showing it's complete, but the checkbox is un-checked, and the data shows "-9/3"

![image](https://user-images.githubusercontent.com/19268864/67219652-0305f980-f3ee-11e9-9331-be794c3c93ee.png)

**Comment by Lalo-ATX** [comment]
issue experienced on non-beta and beta 2.9.70

**Comment by justrealmilk** [comment]
API issue
