### ISSUE TITLE
Progress-bar in Now view hides text

### ISSUE THREAD

**Issue by ovoncovon** [justrealmilk/braytech.org#55]
Standout in languages ​​with large fonts.  

![issue-cssfix](https://user-images.githubusercontent.com/1908806/71945318-d6ea5f80-3209-11ea-9170-245cfd9af84e.jpg)

I was fixed src/components/UI/ProgressBar/styles.css
[[ diff ]](https://github.com/ovoncovon/braytech.org-JA/commit/d6e971a58f1fbbb1168fa603d58a43a6c7a7cf92#diff-7810589d538c41d776bae24bb580da0d)

**Comment by justrealmilk** [comment]
i don't see the problem

**Comment by ovoncovon** [comment]
The top and bottom of the characters are cut off by `overflow: hidden;`
Parent element's  `line-height: ` is small.

![issue-cssfix2](https://user-images.githubusercontent.com/1908806/71967817-36b32b80-3247-11ea-9878-9efd6e9ac556.jpg)

**Comment by justrealmilk** [comment]
ah i see
