### ISSUE TITLE
Hawthorne in Vendor tab (+many others)

### ISSUE THREAD

**Issue by Gentle888** [justrealmilk/braytech.org#59]
Just to look on them newest bounties!

But Hawthorne is preferabble to be first to be in braytech

**Comment by Desyon** [comment]
I think the vendors tab was way more extensive than it is now (listing all planetary vendors + everyone on the tower). Tom decided for some reason (unknown to me) to cut down the number of vendors drastically.

**Comment by justrealmilk** [comment]
Vendors have been deprecated in 2.0.0
