### ISSUE TITLE
Black Armoury seal progress shows up as "Destinations: Curse of Osiris and Warmind"

### ISSUE THREAD

**Issue by barn** [justrealmilk/braytech.org#61]
On latest version as of now.

From viewing "https://braytech.org/triumphs/almost-complete" I have a "Destinations: Curse of Osiris and Warmind" at 7/17, when the badge is out of 39. My black armoury seal is at 7/17 however?

Can I do more debug in to why its getting that? Is there a way to make it spit out an impenetrable mess of JSON at all?

Thanks!

**Comment by justrealmilk** [comment]
This is actually a Bungie error! 😆
