### ISSUE TITLE
Blank screen on iOS / Safari

### ISSUE THREAD

**Issue by bladebunny** [justrealmilk/braytech.org#70]
Seems like after the latest update the page no longer loads correctly on iOS.  I'm not an webdev so not sure how to troubleshoot on device.  I'll see if I can enable dev mode or something and post back any errors i can find out.  It was working fine on iOS just last week.  

Making me sad as this is my new favorite Destiny app!  Thanks so much for such and outstanding community resource.!

**Comment by bladebunny** [comment]
Quick update.  I was able to figure out how to remotely debug.  Looks like I'm getting a body <noscript> element that says I need to enable JS to run the app.  But the thing is, JS is enabled.  Seems like whatever test it's doing to determine JS availability is giving a false negative.  Or there is some other related permission that is not enabled.

**Comment by Thom-Roberts** [comment]
I'm able to get it to load for Safari on ios. Is it a specific page that isn't loading, or the home page?

**Comment by bladebunny** [comment]
The hole home page.   Getting a WSOD (white screen of death).  Checking to see if could be cause by content or pop-up blocking.  Though none of that has changed on my end.

**Comment by bladebunny** [comment]
This is what I see on my end.
![image1](https://user-images.githubusercontent.com/1473399/52141607-1c220c80-260b-11e9-9fd3-d1e4b1cf420b.png)

**Comment by Thom-Roberts** [comment]
I'll take a look when I get home. Thanks for bringing it up!

**Comment by bladebunny** [comment]
Ok.....Resolved it.  Had to blow away my browser cache on Safari.  Which is something I don't usually think of on mobile.  Sorry for the churn!

**Comment by justrealmilk** [comment]
WELL this caching thing is happening surprisingly often 🤔 
Glad you resolved it!
