### ISSUE TITLE
Footer display issues on mobile iOS safari

### ISSUE THREAD

**Issue by inexorableAce** [justrealmilk/braytech.org#75]
iOS 12.1.2 safari 
![a0887855-310c-400c-afc0-23c92b07fa5e](https://user-images.githubusercontent.com/29002828/52357148-984d9300-2a03-11e9-945b-6c177659e1bc.jpeg)

**Comment by justrealmilk** [comment]
Please redesign entire landing page and PR

**Comment by justrealmilk** [comment]
#77
